meta_product_name: "Phasebook"
meta_title: "Phasebook - Open a new chapter in your life"
meta_description: "Phasebook will help you to achieve your reading goals by providing an online environment to discuss your 'reads' and log your reading history"
meta_image: "logo.svg" # should exist in `app/assets/images/`
